//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_commerceApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GamesDtoValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GamesDtoValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("E_commerceApplication.Resources.GamesDtoValidationMessages", typeof(GamesDtoValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background is required.
        /// </summary>
        public static string BackgroundRequired {
            get {
                return ResourceManager.GetString("BackgroundRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count is required.
        /// </summary>
        public static string CountRequired {
            get {
                return ResourceManager.GetString("CountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre is required.
        /// </summary>
        public static string GenreRequired {
            get {
                return ResourceManager.GetString("GenreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid age rating filter.
        /// </summary>
        public static string InvalidAgeFilter {
            get {
                return ResourceManager.GetString("InvalidAgeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid genre fields.
        /// </summary>
        public static string InvalidGenres {
            get {
                return ResourceManager.GetString("InvalidGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rating is from 1 to 5.
        /// </summary>
        public static string InvalidRating {
            get {
                return ResourceManager.GetString("InvalidRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sort field.
        /// </summary>
        public static string InvalidSort {
            get {
                return ResourceManager.GetString("InvalidSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sort order.
        /// </summary>
        public static string InvalidSortOrder {
            get {
                return ResourceManager.GetString("InvalidSortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both sort by and sort order must be provided together.
        /// </summary>
        public static string InvalidSortOrderAndBy {
            get {
                return ResourceManager.GetString("InvalidSortOrderAndBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products are required.
        /// </summary>
        public static string ListProductRequired {
            get {
                return ResourceManager.GetString("ListProductRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo is required.
        /// </summary>
        public static string LogoRequired {
            get {
                return ResourceManager.GetString("LogoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform is required.
        /// </summary>
        public static string PlatformRequired {
            get {
                return ResourceManager.GetString("PlatformRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is required.
        /// </summary>
        public static string PriceRequired {
            get {
                return ResourceManager.GetString("PriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID is required.
        /// </summary>
        public static string ProductIdRequired {
            get {
                return ResourceManager.GetString("ProductIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating is required.
        /// </summary>
        public static string RatingRequired {
            get {
                return ResourceManager.GetString("RatingRequired", resourceCulture);
            }
        }
    }
}
